version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-latest
jobs:
  test-latest: &test-template
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Build all targets
          command: cargo build --all --all-targets
      - run:
          name: Run all tests
          command: cargo test --all
